
// lib/core/get_it/configure_dependency.dart

import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'configure_dependency.config.dart'; // auto-generated by build_runner

final getIt = GetIt.instance;

@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
Future<void> configureDependencies() async {
  // init() registers all dependencies (sync + async)
  getIt.init();

  // allReady() waits until every async singleton finishes initializing
  // (SharedPreferences, Dio, ApiService, etc.) before the app starts
  await getIt.allReady();
}