// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtKdMoMf7oaT50Kfdl87Utb2G6MhvO6eo',
    appId: '1:440816617373:web:f9bebd9f3b13b4c628d174',
    messagingSenderId: '440816617373',
    projectId: 'e-commerce-5bb02',
    authDomain: 'e-commerce-5bb02.firebaseapp.com',
    storageBucket: 'e-commerce-5bb02.firebasestorage.app',
    measurementId: 'G-1SP7QW2VXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmoiVlBLNgdP6C9_7ipCgD0ZMBJA-2qUc',
    appId: '1:440816617373:android:0a8dd2af61eddee628d174',
    messagingSenderId: '440816617373',
    projectId: 'e-commerce-5bb02',
    storageBucket: 'e-commerce-5bb02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vIlzkQ6hTU2wSZZAvTtmTBxCszgtnH4',
    appId: '1:440816617373:ios:f028610f4526621328d174',
    messagingSenderId: '440816617373',
    projectId: 'e-commerce-5bb02',
    storageBucket: 'e-commerce-5bb02.firebasestorage.app',
    iosClientId: '440816617373-ea152t71gh0r46f31ggm5om5jf23ssrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9vIlzkQ6hTU2wSZZAvTtmTBxCszgtnH4',
    appId: '1:440816617373:ios:c065fafd26a2e9c728d174',
    messagingSenderId: '440816617373',
    projectId: 'e-commerce-5bb02',
    storageBucket: 'e-commerce-5bb02.firebasestorage.app',
    iosClientId: '440816617373-3o3qgcsthitq8polm7vhumv85nk1fjpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtKdMoMf7oaT50Kfdl87Utb2G6MhvO6eo',
    appId: '1:440816617373:web:10acdbcf8b594f6028d174',
    messagingSenderId: '440816617373',
    projectId: 'e-commerce-5bb02',
    authDomain: 'e-commerce-5bb02.firebaseapp.com',
    storageBucket: 'e-commerce-5bb02.firebasestorage.app',
    measurementId: 'G-LZNJYC68MM',
  );

}