name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # DI
  get_it: ^9.2.1
  injectable: ^2.7.1+4

  # Networking
  dio: ^5.9.2
  retrofit: ^4.0.3
  json_annotation: ^4.11.0

  # Layout & responsive UI
  flutter_screenutil: ^5.9.3
  fluttertoast: ^9.0.0

  # Media & utilities
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2

  # Icons
  cupertino_icons: ^1.0.8

  # Localization
  easy_localization: ^3.0.8
  flutter_localizations:
    sdk: flutter

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_map: ^6.0.0

  # PDF
  syncfusion_flutter_pdfviewer: ^31.2.12

  # Country / Region pickers
  country_picker: ^2.0.27
  country_state_city_picker: ^1.2.8

  # Real-time
  pusher_channels_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.7.1+4
  json_serializable: ^6.9.4
  retrofit_generator: ^10.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
 